target 'BlueToothAbout' do
pod 'FMDB'
pod 'Masonry'
pod 'CocoaAsyncSocket'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'OCSkeleton'
pod 'ReactiveObjC'
pod 'YYModel'
pod 'YYCache'
pod 'YYImage'
pod 'LKImageKit'
use_frameworks!
end
